# Write your MySQL query statement below
## Report the IDs of the users whose first and last calls on any day were with the same person. Calls are counted regardless of being the caller or the recipient.

WITH ALL_CALLS AS (
    SELECT CALLER_ID, RECIPIENT_ID, CALL_TIME
    FROM CALLS
    UNION
    SELECT RECIPIENT_ID, CALLER_ID, CALL_TIME
    FROM CALLS
),

FIRST_LAST_CALLS AS (
    SELECT 
        DISTINCT CALLER_ID,
        FIRST_VALUE(RECIPIENT_ID) OVER (PARTITION BY CALLER_ID, DATE(CALL_TIME) ORDER BY CALL_TIME) AS FRIST_CALL,
        LAST_VALUE(RECIPIENT_ID) OVER (PARTITION BY CALLER_ID, DATE(CALL_TIME) ORDER BY CALL_TIME ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_CALL
    FROM ALL_CALLS
)

SELECT 
    DISTINCT CALLER_ID AS user_id
FROM FIRST_LAST_CALLS
WHERE FRIST_CALL = LAST_CALL
